name: Testing

on:
  push:
    branches: 
    - '*'
    paths-ignore: 
    - '.github/workflows/**'
    - '**.md'
    - '**.docx'
    - '**.bat'
    - '**.vssettings'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  test:
    name: Testing
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          
      - name: Cache NuGet  
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
          
      - name: Building
        run: dotnet build MathCore.Hosting.WPF/MathCore.Hosting.WPF.csproj -c debug
          
#       - name: Run Tests
#         run: dotnet test Tests/MathCore.WPF.Tests/MathCore.WPF.Tests.csproj -c Debug --no-build
